

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/almendra-paz/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
  rabbitmq:
    host: 192.168.99.100

server:
  port: 8001



management:
  endpoints:
    web:
      exposure:
        include: bus-refresh