---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/almendra-paz/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
server:
  port: 8001